name: "Telegraf collector for rancher hosts"
description: |
  Rancher telegraf integration: collect data from each environment
  host and send it to influx
version:  1.0.0
category: Monitoring
labels:
  io.rancher.orchestration.supported: 'cattle'
