version: '2'
services:
  set-random-password:
    image: alpine:latest
    volumes:
    - /etc:/etc
    command:
    - ash
    - -c
    - echo docker:$$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 32 | head -n 1) | chpasswd
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.global: 'true'

